version: "3.7"
services:
  timemachine:
    hostname: TimeMachine
    #network_mode: "host"
    networks:
      macvlan_network:
        ipv4_address: 100.64.0.4
    environment:
      #- ADVERTISED_HOSTNAME=TimeMachine
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - PASSWORD=timemachine
      #- PASSWORD_FILE=/run/secrets/password
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=0
      - EXTERNAL_CONF=/users
    secrets:
      - password
    restart: unless-stopped
    #ports:
      #- "137:137/udp"
      #- "138:138/udp"
      #- "139:139"
      #- "445:445"
    volumes:
      - /mnt/backups:/opt
      - ./users:/users
    tmpfs:
      - /run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: mbentley/timemachine:smb

secrets:
  password:
    file: ./password.txt

networks:
  macvlan_network:
    external:
      name: mynet